### ISSUE TITLE
Self-XSS

### ISSUE THREAD

**Issue by Marnick39** [tanabe/markdown-live-preview#18]
All js between script tags gets executed. I can't easily find a way to turn this into reflected or stored XSS to attack other users with, but it might be best to tame the beast while it is small. 

![image](https://user-images.githubusercontent.com/17315511/90175529-162bf080-dd97-11ea-8098-af7e764181a2.png)

**Comment by tanabe** [comment]
@Marnick39 

Thanks for opening this issue.
I think also this small at the moment. But I'll fix this.
