### ISSUE TITLE
plz add the flutter source code.

### ISSUE THREAD

**Issue by NicTanghe** [tanabe/markdown-live-preview#26]
plz add the flutter source code.

**Comment by codazoda** [comment]
I realize this is a year old but I'm not sure what you mean. Can you elaborate?

**Comment by NicTanghe** [comment]
I`m sorry for my terrably formatted ticket.
I myself don`t realy remember but i think what i wanted to ask of  you was to provide an example.
I dont realy remember.
My apoligies for such a bad ticket.
