### ISSUE TITLE
Adding Sub-Points to template file

### ISSUE THREAD

**Issue by The-Wolfson** [tanabe/markdown-live-preview#63]
Hi there,
Would you consider changing the template markdown file (index.js) to include sub-bullet points? The 'Ordered' section has sub-points, but the 'Unordered' section does not.
Below is my suggested change:
```
### Unordered
* Item 1
* Item 2
* Item 3
    * Item 3a
    * Item 3b
```
### Unordered
* Item 1
* Item 2
* Item 3
    * Item 3a
    * Item 3b

**Comment by tanabe** [comment]
@The-Wolfson 
Thank you for your suggestion.
I have added sub-points to the template.
